spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: orders
        uri: lb://orders
        predicates:
        - Path=/srva/**
        filters:
        - RewritePath=/orders/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-orders
            fallbackUri: forward:/fallback/orders
      - id: items
        uri: lb:/items
        predicates:
        - Path=/srvb/**
        filters:
        - RewritePath=/items/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-items
            fallbackUri: forward:/fallback/items  
      - id: MQActivityService
        uri: lb://activity
        predicates:
        - Path=/act/**
        filters:
        - RewritePath=/act/(?<segment>.*), /$\{segment} 
    consul:
      discovery:
        instanceId: Gateway
        health-check-interval: 5s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
hystrix:
   dashboard:
       proxy-stream-allow-list: "*"
